# Generated by Django 5.2.5 on 2025-10-09 00:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profileupdaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10, null=True)),
                ('reason', models.TextField()),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('work_handover', models.TextField(blank=True, help_text='Work handover details', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal admin comment not visible to employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave.leaveapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon class for UI display', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='leave_leave_code_add94e_idx')],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveTypePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('applicable_gender', models.CharField(choices=[('all', 'All Genders'), ('male', 'Male Only'), ('female', 'Female Only')], default='all', max_length=10)),
                ('annual_quota', models.DecimalField(decimal_places=2, default=0, help_text='Annual leave quota', max_digits=5)),
                ('accrual_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('accrual_rate', models.DecimalField(decimal_places=2, default=0, help_text='Leave accrued per frequency period', max_digits=5)),
                ('max_per_week', models.PositiveIntegerField(blank=True, help_text='Maximum days per week', null=True)),
                ('max_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum days per month', null=True)),
                ('max_per_year', models.PositiveIntegerField(blank=True, help_text='Maximum days per year', null=True)),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, help_text='Maximum consecutive days', null=True)),
                ('min_notice_days', models.PositiveIntegerField(default=0, help_text='Minimum notice required in days')),
                ('requires_approval', models.BooleanField(default=True)),
                ('auto_approve_threshold', models.PositiveIntegerField(blank=True, help_text='Auto-approve if less than or equal to this many days', null=True)),
                ('carry_forward_enabled', models.BooleanField(default=False)),
                ('carry_forward_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum days that can be carried forward', max_digits=5)),
                ('carry_forward_expiry_months', models.PositiveIntegerField(default=12, help_text='Months after which carried forward leave expires')),
                ('min_tenure_days', models.PositiveIntegerField(default=0, help_text='Minimum days of employment required')),
                ('available_during_probation', models.BooleanField(default=True)),
                ('include_weekends', models.BooleanField(default=False, help_text='Whether weekends count as leave days')),
                ('include_holidays', models.BooleanField(default=False, help_text='Whether holidays count as leave days')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_roles', models.ManyToManyField(blank=True, to='accounts.role')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
            options={
                'ordering': ['leave_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accrued_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('used_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Manual adjustments by admin', max_digits=7)),
                ('used_this_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_accrual_date', models.DateField(blank=True, null=True)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavetypepolicy')),
            ],
            options={
                'ordering': ['user__username', 'leave_type__name', '-year'],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavetypepolicy'),
        ),
        migrations.CreateModel(
            name='LeaveCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10, null=True)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaveapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='leave_leave_date_2b5cda_idx'), models.Index(fields=['user', 'date'], name='leave_leave_user_id_bda6d6_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='leavetypepolicy',
            index=models.Index(fields=['leave_type', 'is_active'], name='leave_leave_leave_t_156799_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetypepolicy',
            index=models.Index(fields=['effective_from', 'effective_to'], name='leave_leave_effecti_384dae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavetypepolicy',
            unique_together={('name', 'leave_type')},
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'year'], name='leave_leave_user_id_029202_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['leave_type', 'year'], name='leave_leave_leave_t_35d9c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['user', 'status'], name='leave_leave_user_id_2d6bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['leave_type', 'status'], name='leave_leave_leave_t_3b748e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_leave_start_d_6dd5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['applied_at'], name='leave_leave_applied_2c04d4_idx'),
        ),
    ]
