# Generated by Django 5.2.5 on 2025-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_add_default_to_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypepolicy',
            name='max_occurrences_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum number of leave occurrences per month (can be fractional like 1.5)', max_digits=5, null=True),
        ),
    ]
