# Generated by Django 5.2.5 on 2025-10-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_quotation_modal_fields'),
        ('common', '0007_remove_description_fields'),
        ('projects', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_mode',
            field=models.ManyToManyField(blank=True, related_name='projects', to='common.appservice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_signed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mediator_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Advanced', 'Advanced'), ('Paid', 'Received')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Fixed', 'Fixed'), ('Salary', 'Salary')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.quotation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotation_sent',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_party_api_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
