# Generated by Django 5.2.5 on 2025-10-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_quotation_modal_fields'),
        ('projects', '0003_alter_project_app_mode_alter_project_contract_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Fixed', 'Fixed')], max_length=10, null=True),
        ),
    ]
