# Generated by Django 5.2.5 on 2025-10-25 10:38

from django.db import migrations, models
from django.utils import timezone


def generate_project_ids(apps, schema_editor):
    """Generate project IDs for existing projects"""
    Project = apps.get_model('projects', 'Project')
    
    for i, project in enumerate(Project.objects.all().order_by('created_at'), 1):
        # Use creation date for existing projects
        created_date = project.created_at
        date_part = created_date.strftime('%d%m%Y')
        time_part = created_date.strftime('%H%M%S')
        
        # Use sequential number based on order
        project.project_id = f"P{date_part}{time_part}#{i:03d}"
        project.save()


def reverse_generate_project_ids(apps, schema_editor):
    """Remove project IDs"""
    Project = apps.get_model('projects', 'Project')
    Project.objects.update(project_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_folder'),
    ]

    operations = [
        # Add the field first (nullable)
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Populate existing records
        migrations.RunPython(generate_project_ids, reverse_generate_project_ids),
        # Make the field unique and non-nullable
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
