# Generated by Django 5.2.5 on 2025-10-25 10:42

from django.db import migrations, models


def update_project_ids(apps, schema_editor):
    """Update existing project IDs to new format P0001, P0002, etc."""
    Project = apps.get_model('projects', 'Project')
    
    for i, project in enumerate(Project.objects.all().order_by('id'), 1):
        project.project_id = f"P{i:04d}"
        project.save()


def reverse_update_project_ids(apps, schema_editor):
    """Reverse the project ID update"""
    pass  # We can't easily reverse this, but it's not critical


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20251025_1608'),
    ]

    operations = [
        # Update the field length
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        # Update existing project IDs
        migrations.RunPython(update_project_ids, reverse_update_project_ids),
    ]
