# Generated by Django 5.2.7 on 2025-11-17 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_folder_enhancements'),
        ('projects', '0007_auto_20251025_1612'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_paid_to_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manual Recipient Name (If Employee FK is not set)')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank Transfer'), ('COD', 'Cod'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Other', max_length=50)),
                ('details_data', models.JSONField(blank=True, null=True, verbose_name='Payment Details (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amount Payable',
                'verbose_name_plural': 'Amounts Payable',
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmountReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manual Client Name (If Client is not set)')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255, verbose_name='Source of Income')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Received')),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank Transfer'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Other', max_length=50)),
                ('details_data', models.JSONField(blank=True, null=True, verbose_name='Receipt Details (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='clients.client')),
            ],
            options={
                'verbose_name': 'Amount Received',
                'verbose_name_plural': 'Amounts Received',
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='Detail/Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'ordering': ['created_at'],
            },
        ),
    ]
