# Generated by Django 5.2.7 on 2025-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_amountpayable_amountreceived_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('server_name', models.CharField(blank=True, max_length=255, null=True)),
                ('server_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_package', models.CharField(blank=True, max_length=100, null=True)),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('login_url', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_username', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_ftp_access', models.CharField(blank=True, max_length=50, null=True)),
                ('database_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_username', models.CharField(blank=True, max_length=100, null=True)),
                ('db_password', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('server_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('backup_status', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_services', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_domain1', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_domain2', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('left_days', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_renewal', models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], max_length=50, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('renewal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dns_configured', models.BooleanField(default=False)),
                ('nameservers', models.TextField(blank=True, null=True)),
                ('ssl_installed', models.BooleanField(default=False)),
                ('ssl_expiry', models.DateField(blank=True, null=True)),
                ('credentials_user', models.CharField(blank=True, max_length=255, null=True)),
                ('credentials_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_services', models.TextField(blank=True, null=True)),
                ('domain_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Charge in INR', max_digits=10, null=True)),
                ('client_payment_status', models.CharField(blank=True, choices=[('None', 'None'), ('Received', 'Received'), ('Pending', 'Pending')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], max_length=50, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('None', 'None'), ('Client', 'Client'), ('Company', 'Company')], max_length=20)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ManyToManyField(blank=True, related_name='domains', to='projects.project')),
            ],
        ),
    ]
