# Generated by Django 5.2.7 on 2025-11-10 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_projectdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmountPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Bank", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amounts_payable",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amount Payable",
                "verbose_name_plural": "Amounts Payable",
                "ordering": ["-date", "created_at"],
            },
        ),
    ]
