# Generated by Django 5.2.7 on 2025-11-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_amountpayable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amountpayable",
            name="project",
        ),
    ]
