# Generated by Django 5.2.7 on 2025-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_amountpayable_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountpayable",
            name="details_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Payment Details Data"
            ),
        ),
        migrations.AlterField(
            model_name="amountpayable",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Bank", "Bank Transfer"),
                    ("COD", "Cod"),
                    ("UPI", "UPI"),
                    ("Cheque", "Cheque"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
