# Generated by Django 5.2.7 on 2025-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_amountpayable_details_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amountpayable",
            name="details_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Payment Details (JSON)"
            ),
        ),
    ]
