# Generated by Django 5.2.7 on 2025-11-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_amountpayable_details_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="amountpayable",
            name="paid_to_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
