# Generated by Django 5.2.7 on 2025-11-11 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_add_folder_enhancements"),
        ("projects", "0013_amountpayable_paid_to_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmountReceived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Source of Income"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Amount Received",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Bank", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                (
                    "details_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Receipt Details (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_made",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amount Received",
                "verbose_name_plural": "Amounts Received",
                "ordering": ["-date", "created_at"],
            },
        ),
    ]
