# Generated by Django 5.2.7 on 2025-11-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_amountreceived"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountreceived",
            name="manual_client_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Manual Client Name (If Client is not set)",
            ),
        ),
    ]
