# Generated by Django 5.2.7 on 2025-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_amountreceived_manual_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountpayable",
            name="manual_paid_to_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Manual Recipient Name (If Employee FK is not set)",
            ),
        ),
    ]
