# Generated by Django 5.2.7 on 2025-11-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_amountpayable_manual_paid_to_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
