# Generated by Django 5.2.7 on 2025-11-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_task_due_date_alter_task_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="start_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
