# Generated by Django 5.2.7 on 2025-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_task_due_date_alter_task_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
