# Generated by Django 5.2.7 on 2025-10-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexAllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_per_month', models.PositiveIntegerField()),
                ('is_late', models.BooleanField(default=False)),
                ('is_early', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='policies_fl_code_524299_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlexPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reset_monthly', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_roles', models.ManyToManyField(blank=True, to='accounts.role')),
                ('flex_types', models.ManyToManyField(to='policies.flexallowancetype')),
            ],
        ),
        migrations.CreateModel(
            name='FlexBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('opening_count', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flex_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.flexallowancetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.flexpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='policies_le_code_ba15a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annual_quota', models.PositiveIntegerField(default=0)),
                ('monthly_accrual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward_limit', models.PositiveIntegerField(default=0)),
                ('notice_days', models.PositiveIntegerField(default=0)),
                ('max_consecutive', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_roles', models.ManyToManyField(blank=True, to='accounts.role')),
                ('leave_types', models.ManyToManyField(to='policies.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.leavepolicy')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.leavetype')),
            ],
        ),
        migrations.AddIndex(
            model_name='flexpolicy',
            index=models.Index(fields=['name'], name='policies_fl_name_e5bd73_idx'),
        ),
        migrations.AddIndex(
            model_name='flexbalance',
            index=models.Index(fields=['user', 'year_month'], name='policies_fl_user_id_4ba06d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flexbalance',
            unique_together={('user', 'flex_type', 'year_month')},
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['name'], name='policies_le_name_e5bcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'year'], name='policies_le_user_id_3db8ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'leave_type', 'year')},
        ),
    ]
