# Generated by Django 5.2.5 on 2025-10-06 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_designation_created_at_designation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
