# Generated by Django 5.2.7 on 2025-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_technology_created_at_technology_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='common_holi_date_09bb4b_idx')],
            },
        ),
    ]
