# Generated by Django 5.2.7 on 2025-10-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='common_apps_name_ca6956_idx')],
            },
        ),
    ]
