# Generated by Django 5.2.7 on 2025-10-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_appservice_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appservice',
            name='description',
        ),
    ]
