# Generated by Django 5.2.7 on 2025-10-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_appservice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='description',
        ),
    ]
