# Generated by Django 5.2.5 on 2025-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_description_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='can_check_in_on_audit',
            field=models.BooleanField(default=False, help_text="If enabled, employees with this designation can use 'Check In On Audit' button which bypasses time restrictions"),
        ),
    ]
