# Generated by Django 5.2.7 on 2025-10-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category': 'expense_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag'),
        ),
        migrations.AddField(
            model_name='folder',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.directory'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.folder'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.folder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category': 'payment_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category': 'salary_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'purchase_date'], name='assets_expe_project_e31240_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['directory'], name='assets_fold_directo_c096eb_idx'),
        ),
        migrations.AddIndex(
            model_name='filedocument',
            index=models.Index(fields=['folder'], name='assets_file_folder__8f0c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['project', 'date'], name='assets_paym_project_e23024_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['user', 'period_start'], name='assets_sala_user_id_42b811_idx'),
        ),
    ]
