# Generated by Django 5.2.7 on 2025-10-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('status', models.ForeignKey(limit_choices_to={'category': 'client_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_modules', models.ManyToManyField(blank=True, to='accounts.module')),
                ('internal_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('valid_until', models.DateField()),
                ('services', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('status', models.ForeignKey(limit_choices_to={'category': 'quotation_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'status'], name='clients_cli_email_57a42d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrole',
            index=models.Index(fields=['name'], name='clients_cli_name_9528de_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['client', 'date'], name='clients_quo_client__abde44_idx'),
        ),
    ]
