# Generated by Django 5.2.7 on 2025-10-18 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('flat', 'Flat'), ('percent', 'Percent')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='domain_registration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email_hosting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='server_hosting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='service_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signatory_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signatory_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_signatures/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ssl_certificate',
            field=models.JSONField(default=dict),
        ),
    ]
