# Generated by Django 5.2.5 on 2025-10-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_quotation_modal_fields'),
        ('files', '0003_folder_is_employee_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ref', to='files.folder'),
        ),
    ]
