# Generated by Django 5.2.5 on 2025-10-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_probation_notice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field being updated', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.TextField(help_text='New requested value')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for update request', null=True)),
                ('admin_comment', models.TextField(blank=True, help_text="Admin's comment on approval/rejection", null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_pr_user_id_1ace14_idx'), models.Index(fields=['status', 'requested_at'], name='accounts_pr_status_268462_idx')],
            },
        ),
    ]
