# Generated by Django 5.2.7 on 2025-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plain_password'),
        ('accounts', '0004_profileupdaterequest'),
    ]

    operations = [
    ]
