# Generated by Django 5.2.7 on 2025-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251015_0812'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0007_remove_description_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_a18e76_idx',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Auto-generated employee ID like DW0001', max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id', 'email', 'organization', 'joining_date'], name='accounts_us_employe_7c302d_idx'),
        ),
    ]
