# Generated by Django 5.2.5 on 2025-10-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_populate_employee_ids'),
        ('files', '0004_add_folder_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ref', to='files.folder'),
        ),
    ]
