# Generated by Django 5.2.5 on 2025-10-29 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_employee_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Payment'), ('hourly', 'Hourly Payment')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount for fixed payments', max_digits=12)),
                ('amount_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Amount per hour for hourly payments', max_digits=10, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total working hours for hourly payments', max_digits=6, null=True)),
                ('date', models.DateField(help_text='Payment date')),
                ('description', models.TextField(help_text='Payment description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='accounts_em_employe_974b76_idx'), models.Index(fields=['payment_type', 'date'], name='accounts_em_payment_f4f71f_idx')],
            },
        ),
    ]
