# Generated by Django 5.2.7 on 2025-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text="End date of the employee's contract (used for time-bound access).", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text="Start date of the employee's contract (used for time-bound access).", null=True),
        ),
    ]
