# Generated by Django 5.2.7 on 2025-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_contract_end_date_user_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_check_in_on_audit',
            field=models.BooleanField(default=False, help_text="If enabled, employees with this role can use 'Check In On Audit' button which bypasses time restrictions"),
        ),
    ]
