# Generated by Django 5.2.5 on 2025-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_unique_together_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_employee_folder',
            field=models.BooleanField(default=False),
        ),
    ]
