# Generated by Django 5.2.5 on 2025-10-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_folder_enhancements'),
        ('files', '0003_folder_is_employee_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='folder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='clients.client'),
        ),
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Gray')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='folder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_client_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_system_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
