# Generated by Django 5.2.7 on 2025-10-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        ('common', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.leavetype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category': 'leave_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeadjustment',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='timeadjustment',
            name='flex_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.flexallowancetype'),
        ),
        migrations.AddField(
            model_name='timeadjustment',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category': 'adjustment_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.statuschoice'),
        ),
        migrations.AddField(
            model_name='timeadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['content_type', 'object_id', 'level'], name='attendance__content_eef079_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance__user_id_c01e0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'start_date', 'status'], name='attendance__user_id_37f96b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeadjustment',
            index=models.Index(fields=['user', 'date'], name='attendance__user_id_3a4bb3_idx'),
        ),
    ]
