# Generated by Django 5.2.7 on 2025-10-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_break_and_day_end_fields'),
        ('attendance', '0002_initial'),
    ]

    operations = [
    ]
