# Generated by Django 5.2.7 on 2025-10-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_admin_reset_count_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='attendance__user_id_6bd9b1_idx',
            old_name='attendance_s_user_id_b8e8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='attendance__user_id_c65738_idx',
            old_name='attendance_s_user_id_0c7b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='attendance__last_ac_f2bdde_idx',
            old_name='attendance_s_last_ac_4b5c8d_idx',
        ),
    ]
