# Generated by Django 5.2.5 on 2025-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_attendance_s_user_id_b8e8c5_idx_attendance__user_id_6bd9b1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('start_break', 'Start Break'), ('end_break', 'End Break'), ('end_of_day', 'End of Day'), ('admin_reset', 'Admin Reset Day')], max_length=20),
        ),
    ]
