# Generated by Django 5.2.7 on 2025-11-25 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_contract_end_date_user_contract_start_date'),
        ('attendance', '0008_alter_sessionlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendanceSetting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_audit_mode_active', models.BooleanField(default=False, help_text="If active, attendance status calculation is bypassed/simplified (e.g., always 'Present') for this specific user.")),
            ],
            options={
                'verbose_name': 'User Attendance Setting',
                'verbose_name_plural': 'User Attendance Settings',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
