# Generated by Django 5.2.7 on 2025-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_userattendancesetting_attendance_late_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_on_audit',
            field=models.BooleanField(default=False, help_text="If True, this attendance was checked in via 'On Audit' mode - bypasses day status calculation"),
        ),
    ]
